<?php

namespace App\Controller;

use Cake\Core\Configure;

class ScheduleAdminController extends AdminController {
	public function index() {
		$this->set("performances", [
			[
				"performance_id" => "1234",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "good",
				"performance_sales" => "50",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1235",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1236",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1237",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1238",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1239",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
				"last" => true
			],
			[], // This signals the beginning of concluded performances
			[
				"performance_id" => "1240",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
			[
				"performance_id" => "1241",
				"performance_name" => "The Tragedy of Macbeth",
				"performance_date" => "1/2/2003",
				"performance_time" => "Today, 2:00pm",
				"performance_hour" => "12",
				"performance_state" => "good",
				"performance_status" => "Active",
				"performance_sales_state" => "bad",
				"performance_sales" => "20",
				"performance_capacity" => "100",
				"performance_open" => "1",
				"performance_canceled" => "0",
			],
		]);

		$this->set("separatorEnabled", false);
	}
}